module Data.XCB.Python.Parse (
  parse,
  emit,
  warning,
  mkImport
  ) where

import Data.XCB.FromXML
import Data.XCB.Types

import Language.Python.Common

import System.FilePath.Glob

parse :: FilePath -> IO [XHeader]
parse fp = do
  files <- globDir1 (compile "*") fp
  fromFiles files

emit :: XHeader -> FilePath -> IO ()
emit header target = undefined

warning :: Token
warning =
  let msg = "This file was automatically generated by xcffib. Do not edit." in
  CommentToken SpanEmpty msg

mkImport :: String -> Statement ()
mkImport name = Import [ImportItem [Ident name ()] Nothing ()] ()
